config/routes.rb
Rails.application.routes.draw do
  # root "users#index"
  # get '/login', to: 'login#index'
  # get '/register', to: 'register#index'
  # get '/users', to: 'user#list'

  resources :users do
    collection do
      get 'list'
    end

    member do
      get 'show_id'
    end
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
    # admin
    @users = User.all

    respond_to do |format|
      format.html { render :index, status: :ok }
      format.json { render json: @users, status: :ok }
    end
  end

  def list
    @users = User.all

    render json: ActiveModel::Serializer::CollectionSerializer.new(@users, each_serializer: UserSerializer)
  end

  def show_id
    render json: { id: User.find(params[:id]).id }
  end

  def show
    # show current user
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # admin
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
    def user_params_with_roles
      params.require(:user).permit(:username, :password, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h1>Authentication</h1>
<form id="login" name="login">
<div style="margin-bottom: 4px;">
  <input type="text" id="username" name="username" placeholder="Username" />
</div>
<div>
  <input type="password" id="password" name="password" placeholder="Password" />
</div>
<form>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
<div style="margin-bottom: 4px;">
  <div>
    <%= form.label :username %>
  </div>
  <div>
    <%= form.text_field :username %>
  </div>
  <div>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
</div>
<div style="margin-bottom: 4px;">
  <div>
    <%= form.label :password %>
  </div>
  <div>
    <%= form.password_field :password %>
  </div>
  <div>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
</div>
<div style="margin-bottom: 4px;">
  <%= form.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h3>Available users</h3>
<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to user.id, user %>
    | <a href="<%= user_path(user) %>" target="_blank"><%= user.username %></a>
    | <%= user.role %>
    | <%=  link_to "Edit", "/users/#{user.id}/edit" %>
  </li>
<% end %>

<%= link_to "Register", new_user_path %>
</ul>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %></h1>

<p> Your role: <%= @user.role %> </p>

<%= link_to "Remove account", user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>